- hosts: servera
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest

- hosts: servera
  tasks:
  - name: install the latest version of telnet
    yum:
      name: telnet
      state: latest